import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Simple BSC React App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div className="col">
        <div className="logo">
          <Image src={"/logo.png"} width={400} height={140} alt="logo" />
        </div>
        <div className="button--primary">Connect</div>
        <div className="button--fixed">Connect</div>
        <div className="intro">
          The BNB Reward Pool with the tastiest daily return and lowest dev fee
        </div>

        <div className="form">
          <div className="form__row">
            <div className="form__row--title">Contract</div>
            <div className="form__row--content">0 BNB</div>
          </div>
          <div className="form__row">
            <div className="form__row--title">Wallet</div>
            <div className="form__row--content">0 BNB</div>
          </div>
          <div className="form__row">
            <div className="form__row--title">Your Beans</div>
            <div className="form__row--content">0 BEANS</div>
          </div>

          <div className="input-field">
            <input type="number" className="input" />
            <p className="token">BNB</p>
          </div>
          <div className="button--secondary">BAKE BEANS</div>
          <div className="divider"></div>
          <div className="row">
            <div className="reward">Your Rewards</div>
            <div className="coin-amount">0 BNB</div>
          </div>
          <div className="row">
            <div className="button--secondary">BAKE BEANS</div>
            <div className="button--secondary">BAKE BEANS</div>
          </div>
        </div>

        <div className="info">
          <div className="info__header">Nutrition Facts</div>
          <div className="row">
            <div className="info__text">Daily Return</div>
            <div className="info__text">8%</div>
          </div>
          <div className="row">
            <div className="info__text">APR</div>
            <div className="info__text">2,920%</div>
          </div>
          <div className="row">
            <div className="info__text">Dev Fee</div>
            <div className="info__text">3%</div>
          </div>
        </div>

        <div className="form">
          <div className="refer__header">Referral Link</div>
          <input className="refer__link" value={"modified link here"} />

          <div className="refer__info">
            Earn 12% of the BNB used to bake beans from anyone who uses your
            referral link
          </div>
        </div>
        <div className="social-media">
          <div className="social-media__item">
            <Image src={"/bsc.png"} width={50} height={50} alt="bsc" />
          </div>
          <div className="social-media__item">
            <Image
              src={"/telegram.png"}
              width={50}
              height={50}
              alt="telegram"
            />
          </div>
          <div className="social-media__item">
            <Image src={"/twitter.png"} width={50} height={50} alt="twitter" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
